[2024-11-26T15:31:21.595+0000] {scheduler_job_runner.py:769} ERROR - Executor reports task instance <TaskInstance: amazon_pipeline.extract_data manual__2024-11-26T15:31:18.561037+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
